name: union_shop
description: "A Flutter project for the University of Portsmouth union shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  firebase_core: 4.0.0
  firebase_auth: 6.0.0
  cloud_firestore: 6.0.0
  js: 0.7.1
  cupertino_icons: 1.0.8
  intl: 0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.6.1
  build_runner: ^2.4.0
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.1

flutter:
  uses-material-design: true
